name: Wild
version: ${project.version}
main: io.wildernesstp.Main
api-version: 1.13
softdepend: [ FabledKingdoms, Factions, Feudal, Residence, Towny, WorldGuard, GriefPrevention, Vault ]

commands:
    wildernesstp:
        description: Managing WilderenessTP.
        aliases: [ wilderness, wildtp, wtp ]
    wild:
        description: Teleport to a random place.
        aliases: [rtp]
    getWorld:
        description: Debug command
        aliases: [getloc]